# Generated by Django 2.0.4 on 2018-05-21 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('when', models.DateTimeField(auto_now_add=True, null=True)),
                ('removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('when', models.DateTimeField(auto_now_add=True, null=True)),
                ('removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stream/static/images')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('when', models.DateTimeField(auto_now_add=True, null=True)),
                ('removed', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby', to='stream.Category')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lobbies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LobbyMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='stream.Lobby')),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, null=True)),
                ('removed', models.BooleanField(default=False)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderators', to='stream.Lobby')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='stream/static/images')),
                ('when', models.DateTimeField(auto_now_add=True, null=True)),
                ('removed', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stream/static/images')),
                ('title', models.CharField(max_length=50)),
                ('URL', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('tag', models.IntegerField(choices=[(0, 'Guest'), (1, 'Sponsor'), (2, 'Player'), (3, 'Main')], default=0)),
                ('when', models.DateTimeField(auto_now_add=True, null=True)),
                ('removed', models.BooleanField(default=False)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='stream.Lobby')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lobbymembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='stream.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='lobby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stream.Lobby'),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
