# Generated by Django 2.0.5 on 2018-05-17 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='when',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='lobby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stream.Lobby'),
        ),
        migrations.AddField(
            model_name='comment',
            name='when',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lobby',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lobby',
            name='when',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='moderator',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moderator',
            name='when',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='when',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='when',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stream/static/images'),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='lobby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderators', to='stream.Lobby'),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='stream/static/images'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stream/static/images'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to=settings.AUTH_USER_MODEL),
        ),
    ]
