# Generated by Django 2.0.5 on 2018-05-17 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_auto_20180517_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='stream.Lobby')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobbies', to='stream.Profile')),
            ],
        ),
        migrations.AlterField(
            model_name='moderator',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderators', to=settings.AUTH_USER_MODEL),
        ),
    ]
