# Generated by Django 2.0.4 on 2018-05-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.IntegerField(choices=[(0, 'Pornographic content.'), (1, 'Copyright infringement.'), (2, 'Racist content.')]),
        ),
    ]
