# Generated by Django 2.0 on 2018-05-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='lobby_type',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Private')], default=0),
        ),
    ]
