# Generated by Django 2.0.5 on 2018-05-17 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_auto_20180517_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby_Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='stream.Lobby')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobbies', to='stream.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile_lobby',
            name='lobby',
        ),
        migrations.RemoveField(
            model_name='profile_lobby',
            name='member',
        ),
        migrations.DeleteModel(
            name='Profile_Lobby',
        ),
    ]
