# Generated by Django 2.0.4 on 2018-05-31 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stream', '0003_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.PositiveIntegerField(null=True)),
                ('template', models.IntegerField(choices=[(0, '{} has subscribed to you'), (1, '{} has started a stream: {} in {}'), (2, 'Your stream has been updated as {}'), (3, 'Your stream has been removed due to {}'), (4, '{} has created a lobby: {}'), (5, 'You have been accepted as a member in the lobby: {}'), (6, 'You have been rejected as a member in the lobby: {}'), (7, '{} has commented in lobby: {}'), (8, 'Your comment has been removed due to {}')])),
                ('when', models.DateTimeField(auto_now_add=True, null=True)),
                ('removed', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('target_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='contenttypes.ContentType')),
            ],
        ),
    ]
