# Generated by Django 2.0.4 on 2018-05-31 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('stream', '0003_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.PositiveIntegerField(null=True)),
                ('template', models.IntegerField(choices=[(0, 'username has subscribed to you'), (1, 'username has started a stream: streamname in lobbyname'), (2, 'Your stream has been updated as streamtag'), (3, 'Your stream has been removed due to reportreason'), (4, 'username has created a lobby: lobbyname'), (5, 'username has commented in lobby: lobbyname'), (6, 'You have been accepted as a member in the lobby: lobbyname'), (7, 'You have been rejected as a member in the lobby: lobbyname'), (8, 'Your comment has been removed due to reportreason')])),
                ('when', models.DateTimeField(auto_now_add=True, null=True)),
                ('removed', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('target_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='contenttypes.ContentType')),
            ],
        ),
    ]
