# Generated by Django 2.0.5 on 2018-05-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_lobby_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
