# Generated by Django 2.0 on 2018-05-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_lobbymembership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='when',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
