# Generated by Django 2.0 on 2018-06-01 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0004_integer_field_reason'),
        ('stream', '0006_report_when'),
        ('stream', '0004_notification'),
    ]

    operations = [
    ]
