# Generated by Django 2.0 on 2018-06-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0008_auto_20180601_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='pub_token',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='stream',
            name='session_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='stream',
            name='sub_token',
            field=models.CharField(default='', max_length=400),
        ),
    ]
