# Generated by Django 2.0.5 on 2018-05-18 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0008_auto_20180518_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lobby_membership',
            old_name='owner',
            new_name='member',
        ),
    ]
