# Generated by Django 2.0.5 on 2018-05-18 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0009_auto_20180518_1055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lobby_Membership',
            new_name='Membership',
        ),
    ]
