# Generated by Django 2.0.5 on 2018-06-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0010_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='online_status',
            field=models.BooleanField(default=True),
        ),
    ]
