# Generated by Django 2.0.5 on 2018-05-18 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0010_auto_20180518_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='LobbyMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='stream.Lobby')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='stream.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='membership',
            name='lobby',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='member',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
