# Generated by Django 2.0.4 on 2018-06-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0011_online_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='template',
            field=models.IntegerField(choices=[(0, '{target.owner.username} has subscribed to you'), (1, '{target.owner.username} has started a stream:         {target.title} in {target.lobby.name}'), (2, 'Your stream has been updated as {target.get_tag}'), (3, 'Your stream has been removed due to {target.get_reason}'), (4, '{target.owner.username} has created a lobby: {target.name}'), (5, 'You have been accepted as a member in the lobby:         {target.lobby.name}'), (6, 'You have been rejected as a member in the lobby:         {target.lobby.name}'), (7, '{target.owner.username} has commented in lobby: {target.lobby.name}'), (8, 'Your comment has been removed due to {target.get_reason}')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
