# Generated by Django 2.0.5 on 2018-05-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0011_auto_20180518_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='URL',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
