from django.urls import path
# from stream.views import home, lobby, management, stream, subscription
from stream.api import lobby, stream, subscription, comment, category, report, profile, moderator, lobby_views, lobby_membership
app_name = 'stream'

urlpatterns = [
    # path('', home.HomeView.as_view(), name='home'),
    # path('lobby/<int:pk>',
    #      lobby.DetailView.as_view(), name='lobby_detailview'),
    # path('managelobby/<int:pk>',
    #      management.DetailView.as_view(), name='manage_detailview'),
    # path('managelobby/<int:pk>/edit',
    #      management.LobbyFormView.as_view(), name='lobby_edit'),
    # path('managelobby/<int:pk>/remove',
    #      management.RemoveView.as_view(), name='manage_remove'),
    # path('managelobby/<int:pk>/tags',
    #      management.TagsView.as_view(), name='manage_tags'),
    # path('lobby/<int:pk>/comments/',
    #      lobby.CommentView.as_view(), name='lobby_commentview'),
    # path('update_stream/<int:pk>/',
    #      stream.UpdateView.as_view(), name='stream_updateview'),
    # path('delete_stream/<int:pk>/',
    #      stream.DeleteView.as_view(), name='stream_deleteview'),
    # path('lobby/<int:pk>/create_stream/',
    #      stream.CreateView.as_view(), name='stream_createview'),
    # path('lobby/subscribe/',
    #      subscription.SubscribeView.as_view(), name='subscribe'),
    # path('lobby/<int:pk>/join_lobby',
    #      lobby.JoinView.as_view(), name='join_lobby'),
    path('api/stream',
         stream.StreamAPI.as_view(), name='api_stream'),
    path('api/lobby',
         lobby.LobbyAPI.as_view(), name='api_lobby'),
    path('api/comment',
         comment.CommentAPI.as_view(), name='api_comment'),
    path('api/category',
         category.CategoryAPI.as_view(), name='api_category'),
    path('api/subscription',
         subscription.SubscriptionAPI.as_view(), name='api_subscription'),
    path('api/report',
         report.ReportAPI.as_view(), name='api_report'),
    path('api/profile',
         profile.ProfileAPI.as_view(), name='api_profile'),
    path('api/moderator',
         moderator.ModeratorAPI.as_view(), name='api_moderator'),
    path('api/lobby_views',
         lobby_views.LobbyViewsAPI.as_view(), name='api_lobby_views'),
    path('api/lobby_membership',
         lobby_membership.LobbyMembershipAPI.as_view(), name='api_lobby_membership'),
    path('api/lobby',
         lobby.LobbyAPI.as_view(), name='api_lobby'),
]
